### ISSUE TITLE
Fix code scanning alert - Full server-side request forgery

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1315]
Tracking issue for:
- [x] https://github.com/OWASP/BLT/security/code-scanning/33

![image](https://github.com/OWASP/BLT/assets/128622481/837160ae-34dd-4316-8653-f5b48a35e4f0)

**Comment by JisanAR03** [comment]
I fix this one /assign

**Comment by JisanAR03** [comment]
fixed by #1585

**Comment by Himanshu-639** [comment]
Hi team,

While reviewing the fix for SSRF in InviteCreate, I noticed that the issue may still exist. The function constructs a URL using user input and makes an external request without validating against private/internal IPs.

Specifically, rebuild_safe_url() does not prevent SSRF if an attacker provides an email like attacker@169.254.169.254. This could still allow requests to internal services.

I can make the necessary changes to fix this so assign this to me.

Thanks!

**Comment by gojo-satorou-v7** [comment]
This was fixed #3764

**Comment by gojo-satorou-v7** [comment]
Mention detected. 

This issue seems to be closed, please guide the next steps.
